polls/urls.py
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', views.PollDetailView.as_view(), name='detail'),
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
    url(r'^new_poll/', views.CreatePoll.as_view(), name='new_poll'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^register/$', views.register, name='register'),
)

pollsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
import polls.urls

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'pollsite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include(polls.urls, namespace="polls")),
)

polls/models.py
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class Poll(models.Model):
    author = models.ForeignKey(User)
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField("Date published")

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) < self.pub_date < now

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('polls:detail', args=[str(self.id)])

    def __unicode__(self):
        return self.question

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)

    def __unicode__(self):
        return self.choice_text


class Vote(models.Model):
    choice = models.ForeignKey(Choice)
    user = models.ForeignKey(User)

polls/forms.py
from django import forms
from polls import models
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class PollForm(forms.ModelForm):

    choice1 = forms.CharField(max_length=128, required=True)
    choice2 = forms.CharField(max_length=128, required=True)
    choice3 = forms.CharField(max_length=128, required=False)
    choice4 = forms.CharField(max_length=128, required=False)
    choice5 = forms.CharField(max_length=128, required=False)

    def save(self, *args, **kwargs):
        poll = super(PollForm, self).save(*args, **kwargs)

        choices = sorted([text for name, text in self.cleaned_data.items() if name.startswith('choice') and text != ''])

        for choice in choices:
            poll.choice_set.create(choice_text=choice)

        return poll

    class Meta:
        model = models.Poll
        fields = ('question', 'author', 'pub_date')
        widgets = {
            'pub_date': forms.HiddenInput,
            'author': forms.HiddenInput,
        }
        labels = {
            'question': "What is your question?"
        }

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User, AnonymousUser
from polls.models import Poll, Choice, Vote
from polls.forms import UserForm, PollForm


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_poll_list'

    def get_queryset(self):
        return Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class PollDetailView(generic.DetailView):
    model = Poll
    template_name = 'polls/detail.html'

    def get(self, request, pk, *args, **kwargs):
        p = get_object_or_404(Poll, pk=pk)

        if isinstance(request.user, AnonymousUser):
            return render(request, 'polls/detail.html', {'poll': p, 'error_message': "You are not logged in"})

        if request.user.vote_set.filter(choice__poll=p).exists():
            return redirect(reverse('polls:results', args=(p.id,)))

        return super(PollDetailView, self).get(request, pk, *args, **kwargs)


class ResultsView(generic.DetailView):
    model = Poll
    template_name = 'polls/results.html'

    def get(self, request, pk, *args, **kwargs):
        self.prev_choice = None
        p = get_object_or_404(Poll, pk=pk)
        self.vote_counts = {k.choice_text: k.vote_set.count() for k in p.choice_set.all()}

        if not isinstance(request.user, AnonymousUser):
            if request.user.vote_set.filter(choice__poll=p).exists():
                self.prev_choice = request.user.vote_set.filter(choice__poll=p)[0].choice

        return super(ResultsView, self).get(request, pk, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ResultsView, self).get_context_data(**kwargs)
        context.update({'prev_choice': self.prev_choice})
        context.update({'vote_counts': self.vote_counts})
        return context

class CreatePoll(generic.CreateView):
    model = Poll
    template_name = 'polls/create_poll.html'
    form_class = PollForm

    def get_initial(self):
        initial = super(CreatePoll, self).get_initial()
        author = self.request.user
        initial.update({
            'author': author,
            'pub_date': timezone.now()
        })
        return initial


def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    user = request.user

    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'poll': p, 'error_message': "You didn't select a choice"})
    else:
        if not isinstance(user, AnonymousUser) and user.is_active:
            v = Vote()
            v.choice = selected_choice
            v.user = user
            v.save()
            return redirect(reverse('polls:results', args=(p.id,)))
        else:
            return render(request, 'polls/detail.html', {'poll': p, 'error_message': "You are not logged in"})


def user_login(request):
    context_dict = {}

    user = None

    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request, user)
                return redirect(reverse('polls:index'))
            else:
                context_dict['disabled_account'] = True
                return render(request, 'polls/login.html', context_dict)
        else:
            print "Invalid login details: {0}, {1}".format(username, password)
            context_dict['bad_details'] = True
            return render(request, 'polls/login.html', context_dict)
    else:
        return render(request, 'polls/login.html', context_dict)


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('polls:index'))


def register(request):
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)

        if user_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()
            user = authenticate(username=request.POST['username'], password=request.POST['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
            return redirect(reverse('polls:index'))
        else:
            print user_form.errors
    else:
        user_form = UserForm()

    context_dict = {'user_form': user_form}

    return render(request, 'polls/register.html', context_dict)

templates/polls/base.html
<!DOCTYPE html>
{% load static %}

<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- Bootstrap -->
        <link href="{% static 'css/bootstrap-fluid-adj.css' %}" rel="stylesheet">
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/bootstrap-responsive.css' %}" rel="stylesheet">

        <title>Pollsite - {% block title %} Index {% endblock %}</title>
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
           <div class="navbar-inner">
               <div class="container">
                   <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                       <span class="icon-bar"></span>
                   </button>
                   <a class="brand" href={% url 'polls:index' %}>Pollsite</a>

                   <div class="nav-collapse collapse">
                       <ul class="nav pull-right">
                            {% if user.is_authenticated %}
                                <li class="navbar-text">Welcome, {{ user.username }}!</li>
                                <li><a href={% url 'polls:logout' %}>Logout</a></li>
                           {% else %}
                                <li><a href={% url 'polls:register' %}>Register</a></li>
                                <li><a href={% url 'polls:login' %}>Login</a></li>
                           {% endif %}
                       </ul>
                       <ul class="nav">
                           {% if user.is_authenticated %}
                                <li><a href={% url 'polls:new_poll' %}>Create poll</a></li>
                           {% endif %}
                       </ul>
                    </div>
                   <!--/.nav-collapse -->
               </div>
           </div>
        </div>

        <div class="container">
            <div class="row-fluid">
                <div class="span3">
                    <div class="well sidebar-nav">
                        <!--- Empty for the timebeing -->
                    </div>
                    <!--/.well -->
                </div>
                <!--/span-->
                <div class="span9">
                    {% block body_block %}
                    {% endblock %}
                </div>
                <!--/span-->
            </div>
            <!--/row-->
        </div>
        <!--/.fluid-container-->

        <hr>

    <script src="{% static 'js/jquery-2.1.1.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

templates/polls/create_poll.html
{% extends 'polls/base.html' %}

{% block title %}Create a new poll{% endblock %}

{% block body_block %}
    <form id="poll_form" method="post" action=""
            enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.as_p }}

        <!-- Display each form. The as_p method wraps each element in a paragraph
             (<p>) element. This ensures each element appears on a new line,
             making everything look neater. -->

        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Create" />
    </form>
{% endblock %}

templates/polls/detail.html
{% extends 'polls/base.html' %}

{% block body_block %}
    <h1>{{ poll.question }}</h1>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="{% url 'polls:vote' poll.id %}" method="post">
        {% csrf_token %}
        {% for choice in poll.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}
        <input type="submit" value="Vote" />
    </form>

    <br />

    <a href='{% url 'polls:results' poll.id %}'>View Results</a></li>
{% endblock %}

templates/polls/index.html
{% extends 'polls/base.html' %}
{% load static %}

{% block body_block %}
<div class="hero-unit">
    <h3>Latest Polls</h3>
    {% if latest_poll_list %}
        <ul>
        {% for poll in latest_poll_list %}
            <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>No polls are available.</p>
    {% endif %}

    {% if user.is_authenticated %}
        <a href={% url 'polls:new_poll' %}>Create a new poll</a>
    {% endif %}
</div>
{% endblock %}

templates/polls/login.html
{% extends "polls/base.html" %}

{% block title %}Login{% endblock %}

{% block body_block %}
    <h1>Login to Pollsite</h1>

    <form id="login_form" method="post" action="">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="50" />
        <br />
        Password: <input type="password" name="password" value="" size="50" />
        <br />

        <input type="submit" value="submit" />
    </form>
{% endblock %}

templates/polls/register.html
{% extends 'polls/base.html' %}


{% block body_block %}
    {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="/polls">Return to the homepage.</a><br />
    {% else %}
    <strong>register here!</strong><br />

    <form id="user_form" method="post" action=""
            enctype="multipart/form-data">

        {% csrf_token %}

        <!-- Display each form. The as_p method wraps each element in a paragraph
             (<p>) element. This ensures each element appears on a new line,
             making everything look neater. -->
        {{ user_form.as_p }}

        <!-- Provide a button to click to submit the form. -->
        <input type="submit" name="submit" value="Register" />
    </form>
    {% endif %}
{% endblock %}

templates/polls/results.html
{% extends 'polls/base.html' %}
{% load static %}

{% block body_block %}
    <h1>{{ poll.question }}</h1>

    {% if prev_choice %}
        <p>You chose {{ prev_choice.choice_text }}</p>
    {% endif %}

    <ul>
        {% for choice in poll.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.vote_set.count }} vote{{ choice.votes|pluralize}}</li>
        {% endfor %}
    </ul>

    <a href={% url 'polls:index' %}>Back to index</a>

    <script src={% static 'js/jquery-2.1.1.js' %}></script>
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/modules/exporting.js"></script>

    <div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: auto; position:relative; right:120px" class='container'></div>

    <script type='text/javascript'>
    $(function() {
        var chart = new Highcharts.Chart({
            chart: {
                renderTo: 'container',
                type: 'pie',
            },

            title: {
                text: "Results of '{{ poll.question }}'"
            },

            plotOptions: {
                pie: {
                    borderColor: '#000000',
                    innerSize: '50%'
                }
            },

            series: [{
                data: [
                    {% for k, v in vote_counts.items %}
                        {% if v != 0 %}
                            ['{{ k }}', {{ v }}],
                        {% endif %}
                    {% endfor %}
                    ]}]
        },
        // using

        function(chart) { // on complete

            var xpos = '50%';
            var ypos = '50%';
            var circleradius = 100;

        // Render the circle
        chart.renderer.circle(xpos, ypos, circleradius).attr({
            fill: '#FFFFFF',
        }).add();
        });
    });
    </script>

    </div>


{% endblock %}